version: '3'

services:
  utility:
    image: buzzingpixel/utility:1.1.0
    container_name: utility-corbomite-queue
    environment:
      HOSTNAME: utility-corbomite-queue
    volumes:
      - .:/app
      - db-volume:/db-volume
    command: bash -c "chmod +x /app/scripts/devUtilityScript.sh && /app/scripts/devUtilityScript.sh"
    networks:
      corbomite-queue-network:
  php:
    image: buzzingpixel/php7.2:1.0.6
    container_name: php-corbomite-queue
    environment:
      HOSTNAME: php-corbomite-queue
      COMPOSER_HOME: /composer-home-volume
    volumes:
      - .:/app:delegated
      - ./serverConfig/php/php-custom-config.ini:/usr/local/etc/php/conf.d/php-custom-config.ini:delegated
      - ./serverConfig/php/php-config-dev.ini:/usr/local/etc/php/conf.d/php-env-config.ini:delegated
      - composer-home-volume:/composer-home-volume:delegated
    networks:
      corbomite-queue-network:
  db:
    image: buzzingpixel/mariadb:2.0.1
    container_name: db-corbomite-queue
    restart: always
    environment:
      HOSTNAME: db-corbomite-queue
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: site
      MYSQL_DATABASE: site
      MYSQL_PASSWORD: secret
    user: "1000:50"
    volumes:
      - .:/app:delegated
    ports:
      - "17296:3306"
